export const ADD_COMPANY = "ADD_COMPANY";
export const GET_COMPANIES = "GET_COMPANIES";
export const RESET_CREATE = "RESET_CREATE";
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const GET_EMPLOYEE_DETAIL = 'GET_EMPLOYEE'
